# Лабораторная работа №1
## Выполнил студент группы БФИ2302 АндреевАМ

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [15]:
print("Hello, World!")

Hello, World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [1]:
import random
import time
import numpy as np

In [115]:
def userInput(prompt, default):
    u = input(prompt)
    return int(u) if u.strip() else default

def matrixGen(func):
    def wrapper():
        m = userInput("Rows: ",50)
        n = userInput("Columns: ",50)
        user_min = userInput("MinRand: ",-250)
        user_max = userInput("MaxRand: ",1000)
        return func(m,n,user_min,user_max)
    return wrapper

def timer(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        value = func(*args, **kwargs)
        print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))
        return value
    return wrapper

@matrixGen
@timer
def nestedFor(m,n,user_min,user_max):
    matrix = []
    for row in range(m):
        a = []
        for col in range(n):
            a.append(random.randint(user_min,user_max))
        matrix.append(a)
    return matrix

@matrixGen
@timer
def listComp(m,n,user_min,user_max):
    return [[random.randint(user_min,user_max) for _ in range(n)] for _ in range(m)]

@matrixGen
@timer
def numPy(m,n,user_min,user_max):
    return np.random.randint(user_min,user_max+1,size=(m,n))

In [116]:
print(nestedFor())

--- 2 ms ---
[[207, 254, -140, 759, 486, 254, 808, 786, 29, 827, -120, 22, 942, 478, 378, 796, 994, 560, 922, 886, 979, -24, -79, 180, -156, 175, -73, 719, 651, 993, 114, 249, 395, 187, 757, 283, 586, 880, -17, -28, 314, 214, -219, 818, 127, 591, -23, 94, -95, 196], [913, 499, 648, -11, 842, 253, 434, 949, 527, 303, -173, 345, -185, 83, 756, 891, 215, 806, 608, 67, 959, 210, 747, 26, -30, -244, 500, 142, 755, 493, 164, 128, 55, 979, 891, 554, 784, 732, 979, 409, 66, -101, 705, 973, 151, 237, 843, 534, 205, 212], [288, -219, 168, -65, -30, 353, 711, 118, 343, 744, 437, 732, 561, 822, -179, 354, 472, 417, -7, 282, 548, 168, 984, 584, 87, 356, 564, 698, -99, 197, 542, -94, 344, 886, 85, 958, 559, -112, 368, 799, -125, 566, 386, 855, 941, 898, -210, 857, 325, -225], [218, 207, 699, 290, 842, 445, 516, -25, 177, 834, 8, 944, 792, 223, -99, 327, -237, 92, 584, 777, 905, -158, -111, -147, 835, 776, 571, -193, -143, 319, -238, 396, 846, 378, 535, 334, 400, 321, 13, 723, 471, 346, 25, 573, 789,

In [117]:
print(listComp())

--- 1 ms ---
[[633, 39, 555, 186, 705, 168, -13, 283, 886, 775, 643, 379, 522, 180, 132, 805, -230, 442, 68, 832, 925, 299, 590, -193, 322, 333, 513, -139, 205, 840, 55, 354, 309, 665, 809, 698, 292, 996, 339, 106, 298, 282, 588, 376, -166, 112, 364, 372, 268, 264], [37, 514, 489, 234, -1, 937, -67, 922, 729, 475, 858, 682, 674, 929, -38, 240, 751, 237, 485, 702, 493, 56, 530, 870, -67, 238, 35, 934, -145, -98, 948, -30, 900, 89, 146, 430, -132, 372, -126, 997, 44, 471, -247, 15, 709, 989, 178, 441, 681, 649], [382, 236, 304, 226, -105, 892, -68, 238, 429, 616, 605, 709, -196, 195, -85, 909, 574, 599, -51, -129, 125, 581, 397, 406, 10, 577, 774, 232, 514, 554, 788, 791, 641, 332, -169, 635, 959, 381, 593, 399, 738, 710, -23, 247, 560, 334, 270, 707, 768, 745], [-141, 865, 681, 587, 426, 227, 261, -166, 5, 586, 799, 701, 982, 251, 287, -95, 389, 527, 532, 722, -208, 970, -31, -23, 83, -174, 927, 950, 669, -176, -115, 505, -163, 887, 734, 146, 276, -149, 642, -78, 493, 8, 92, 858, 960, -

In [118]:
print(numPy())

--- 0 ms ---
[[ 129  216  410 ...  298  -27  -92]
 [ 244  386 -234 ...   61  536  257]
 [-108  515  201 ...  132  687 -214]
 ...
 [ 358  999  470 ...  509  116   76]
 [ 530 -226  512 ...  309  840  -94]
 [ 914  337  954 ...  288  967  525]]


### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [ ]:
# Сортировка выбором.
# Берётся срез массива, в котором минимальный элемент переносят в самый левый угол,
# после чего срез уменьшается и цикл повторяется.



--- 0 ms ---


In [5]:
# Сортировка вставкой.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

--- 0 ms ---


In [6]:
# Сортировка обменом. || Сортировка пузырьком.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

--- 0 ms ---


In [7]:
# Сортировка Шелла.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

--- 0 ms ---


In [8]:
# Быстрая сортировка.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))
    

--- 0 ms ---


In [9]:
# Турнирная сортировка.
start_time = time.time()
#TODO
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

--- 0 ms ---


### Вывод
